services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - test_volume:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: psql-pwd
      POSTGRES_DB: gpns

volumes:
  test_volume: {}
